name: wafelzwaard
version: '1.0-SNAPSHOT'
main: me.verschillend.wafelzwaard.Wafelzwaard
api-version: '1.21'
authors:
  - Verschillend
permissions:
  wafelzwaard.lobby:
    description: Allows use of /lobby and /hub
    default: true